AWSTemplateFormatVersion: "2010-09-09"
Description: "create elastic cache template"

Parameters:
  CacheSubnetGroupName:
    Default: decidim-group
    Type: String
  VpcSecurityGroupId:
    Type: CommaDelimitedList
  ClusterName:
    Type: String
    Default: staging-decidim-redis
  CacheNodeType:
    Type: String
    Default: cache.t2.micro

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'ElastiCache Parameters'
      Parameters:
      - CacheNodeType

Resources:
  ElasticCacheRedis:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      AutoMinorVersionUpgrade: true
      AZMode: single-az
      CacheNodeType: !Ref CacheNodeType
      Engine: redis
      EngineVersion: 5.0.6
      NumCacheNodes: 1
      PreferredAvailabilityZone: ap-northeast-1a
      PreferredMaintenanceWindow: thu:13:00-thu:14:00
      ClusterName: !Ref ClusterName
      CacheSubnetGroupName: !Ref CacheSubnetGroupName
      VpcSecurityGroupIds: !Ref VpcSecurityGroupId
